<a href="https://colab.research.google.com/github/gauravreddy08/learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00 | **PyTorch** Fundamentals 

https://github.com/gauravreddy08/learning-pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-5bec794a-9d71-adc4-0632-81639a4c954e)


## Introduction to **tensors**
### Creating **tensors**

In [3]:
# scalar
scalar = torch.tensor(7)
scalar, scalar.ndim, scalar.item()

(tensor(7), 0, 7)

In [4]:
# vector
vector = torch.tensor([4, 2])
vector, vector.shape, vector.ndim

(tensor([4, 2]), torch.Size([2]), 1)

In [5]:
# matrix
matrix = torch.tensor([[4, 2],
                       [2, 4]])
matrix, matrix.shape, matrix.ndim

(tensor([[4, 2],
         [2, 4]]), torch.Size([2, 2]), 2)

In [6]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 8]]])
tensor, tensor.shape, tensor.ndim

(tensor([[[1, 2, 3],
          [3, 6, 8]]]), torch.Size([1, 2, 3]), 3)

In [7]:
tensor[0][0]

tensor([1, 2, 3])

### Random **tensors**

cause everything is random :)

In [8]:
random_tensor = torch.rand(1, 1, 1, 1, 1, 1, 1, 1, 3, 4)
random_tensor, random_tensor.dtype

(tensor([[[[[[[[[[0.7789, 0.4951, 0.2321, 0.8122],
                 [0.9581, 0.6903, 0.2808, 0.5025],
                 [0.2728, 0.2151, 0.5902, 0.1126]]]]]]]]]]), torch.float32)

In [9]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
tensor = torch.tensor([1, 5, 9], 
                      dtype=torch.float16, 
                      requires_grad=False)
tensor, tensor.device

(tensor([1., 5., 9.], dtype=torch.float16), device(type='cpu'))

### Manipulating **tensors**

In [11]:
tensor+3, torch.add(tensor, 3)

(tensor([ 4.,  8., 12.], dtype=torch.float16),
 tensor([ 4.,  8., 12.], dtype=torch.float16))

In [12]:
tensor-23, torch.subtract(tensor, 23)

(tensor([-22., -18., -14.], dtype=torch.float16),
 tensor([-22., -18., -14.], dtype=torch.float16))

In [13]:
tensor*3, torch.mul(tensor, 3)

(tensor([ 3., 15., 27.], dtype=torch.float16),
 tensor([ 3., 15., 27.], dtype=torch.float16))

In [14]:
tensor/2, torch.divide(tensor, 2)

(tensor([0.5000, 2.5000, 4.5000], dtype=torch.float16),
 tensor([0.5000, 2.5000, 4.5000], dtype=torch.float16))

https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [15]:
matrix, matrix*20

(tensor([[4, 2],
         [2, 4]]), tensor([[80, 40],
         [40, 80]]))

In [16]:
matrix*(matrix*2)

tensor([[32,  8],
        [ 8, 32]])

In [17]:
vector, matrix, vector*matrix

(tensor([4, 2]), tensor([[4, 2],
         [2, 4]]), tensor([[16,  4],
         [ 8,  8]]))

In [18]:
vector @ matrix, torch.matmul(vector, matrix) # not dot product

(tensor([20, 16]), tensor([20, 16]))

http://matrixmultiplication.xyz/

### **Tensor** aggregation

In [19]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x.type(torch.float16)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [21]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [22]:
x.max(), torch.max(x)

(tensor(9), tensor(9))

In [23]:
x = x.type(torch.float16)

x.mean(), torch.mean(x) # could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

(tensor(4.5000, dtype=torch.float16), tensor(4.5000, dtype=torch.float16))

In [24]:
x.sum(), torch.sum(x)

(tensor(45., dtype=torch.float16), tensor(45., dtype=torch.float16))

In [25]:
x.argmin(), torch.argmin(x), x.argmax(), torch.argmax(x)

(tensor(0), tensor(0), tensor(9), tensor(9))

In [26]:
# Reshape 

x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]], dtype=torch.float16), torch.Size([2, 5]))

In [27]:
# View
z = x.view(2, 5)
z[0, 1] = 123
z, x # changing z --> changes x

(tensor([[  0., 123.,   2.,   3.,   4.],
         [  5.,   6.,   7.,   8.,   9.]], dtype=torch.float16),
 tensor([  0., 123.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        dtype=torch.float16))

In [28]:
# Stacking

x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[  0.,   0.,   0.,   0.],
        [123., 123., 123., 123.],
        [  2.,   2.,   2.,   2.],
        [  3.,   3.,   3.,   3.],
        [  4.,   4.,   4.,   4.],
        [  5.,   5.,   5.,   5.],
        [  6.,   6.,   6.,   6.],
        [  7.,   7.,   7.,   7.],
        [  8.,   8.,   8.,   8.],
        [  9.,   9.,   9.,   9.]], dtype=torch.float16)

In [29]:
x = torch.rand(1, 2, 3, 2)
x

tensor([[[[0.4448, 0.6634],
          [0.9926, 0.3367],
          [0.9220, 0.2335]],

         [[0.7106, 0.7215],
          [0.3368, 0.8766],
          [0.0091, 0.7520]]]])

In [30]:
torch.unsqueeze(x, dim=3)

tensor([[[[[0.4448, 0.6634]],

          [[0.9926, 0.3367]],

          [[0.9220, 0.2335]]],


         [[[0.7106, 0.7215]],

          [[0.3368, 0.8766]],

          [[0.0091, 0.7520]]]]])

In [31]:
# Permute

x_img = torch.rand(size=(224, 224, 3))
x_img.size(), x_img.permute((1, 2, 0)).size() # Rearrange the axis/dimensions

(torch.Size([224, 224, 3]), torch.Size([224, 3, 224]))

## **Pytorch** and NumPy

In [32]:
x, x.dtype

(tensor([[[[0.4448, 0.6634],
           [0.9926, 0.3367],
           [0.9220, 0.2335]],
 
          [[0.7106, 0.7215],
           [0.3368, 0.8766],
           [0.0091, 0.7520]]]]), torch.float32)

In [33]:
x_numpy = x.numpy()
x_numpy

array([[[[0.44477975, 0.6633965 ],
         [0.9925507 , 0.33673126],
         [0.92197573, 0.2334826 ]],

        [[0.7106104 , 0.72149795],
         [0.3367799 , 0.8765549 ],
         [0.00908428, 0.75203943]]]], dtype=float32)

In [34]:
x_from_numpy = torch.from_numpy(x_numpy)
x_from_numpy, x_from_numpy.dtype

(tensor([[[[0.4448, 0.6634],
           [0.9926, 0.3367],
           [0.9220, 0.2335]],
 
          [[0.7106, 0.7215],
           [0.3368, 0.8766],
           [0.0091, 0.7520]]]]), torch.float32)

## Seeding the **randomness**

In [35]:
torch.manual_seed(42)
a = torch.rand(3, 4)

torch.manual_seed(42)
b = torch.rand(3, 4)

a==b

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Accessing **PyTorch** by **GPU**

In [37]:
torch.cuda.is_available()

True

In [38]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [40]:
torch.cuda.device_count()

1

### Putting **tensors** on **GPU**

In [41]:
tensor

tensor([1., 5., 9.], dtype=torch.float16)

In [42]:
tensor_on_gpu = tensor.to(device)tensor_on_gpu

tensor([1., 5., 9.], device='cuda:0', dtype=torch.float16)

In [45]:
# tensor_on_gpu.numpy() # Error
tensor_on_gpu.cpu().numpy()

array([1., 5., 9.], dtype=float16)